pipeline {
    agent any

    stages {

        stage('Build Docker Image') {
            steps {
                bat 'cd kle-tech-portal && docker build -t kleportal .'
            }
        }

        stage('Stop Old Container') {
            steps {
                bat 'docker stop kle-container >nul 2>&1 || ver >nul'
                bat 'docker rm kle-container >nul 2>&1 || ver >nul'
            }
        }

        stage('Run New Container') {
            steps {
                bat 'docker run -d --name kle-container -p 5000:5000 kleportal'
            }
        }
    }

    post {
        success {
            echo 'Deployment Successful!'
        }

        failure {
            echo 'Deployment Failed!'
        }
    }
}